export async function GET() {
  const homeStays = [
    {
      id: 1,
      slug: "bloom",
      name: "Bloom",
      address: "Quận Tân Phú, TP. HCM",
      district: "Quận Tân Phú",
      video: "/videos/hsTanPhu.mp4",
      images: [
        "/images/hsTanPhu1P1.jpg",
        "/images/hsTanPhu2P1.jpg",
        "/images/hsTanPhu3P1.jpg",
        "/images/hsTanPhu4P1.jpg",
        "/images/hsTanPhu5P1.jpg",
        "/images/hsTanPhu6P1.jpg",
        "/images/hsTanPhu7P1.jpg",
        "/images/hsTanPhu8P1.jpg",
        "/images/hsTanPhu9P1.jpg",
        "/images/hsTanPhu10P1.jpg",
        "/images/hsTanPhu11P1.jpg",
        "/images/hsTanPhu12P1.jpg",
        "/images/hsTanPhu13P1.jpg",
      ],
      amenities: [
        "máy lạnh",
        "máy chiếu",
        "bếp",
        "nước nóng lạnh",
        "YouTube Premium",
        "Netflix",
      ],
      price: "/images/P-Bloom.png",
      description:
        "Ẩn mình giữa lòng Quận Tân Phú nhộn nhịp, 23st.homestay Bloom là điểm dừng chân lý tưởng cho những tâm hồn yêu thiên nhiên và sự tinh tế. Với thiết kế mở, tràn ngập ánh sáng tự nhiên, kết hợp cùng cây xanh bố trí hài hòa trong từng góc nhỏ, Bloom đem lại cảm giác như đang lạc vào một khu vườn nhỏ yên bình. Nội thất mang hơi hướng hiện đại nhưng không kém phần nhẹ nhàng, mang đến trải nghiệm thư giãn tuyệt đối sau những giờ làm việc căng thẳng.",
    },
    {
      id: 2,
      slug: "tangerine",
      name: "Tangerine",
      address: "Quận Tân Phú, TP. HCM",
      district: "Quận Tân Phú",
      video: "/videos/hsTanPhu.mp4",
      images: [
        "/images/hsTanPhu1P2.jpg",
        "/images/hsTanPhu2P2.jpg",
        "/images/hsTanPhu3P2.jpg",
        "/images/hsTanPhu4P2.jpg",
        "/images/hsTanPhu5P2.jpg",
        "/images/hsTanPhu6P2.jpg",
        "/images/hsTanPhu7P2.jpg",
        "/images/hsTanPhu8P2.jpg",
        "/images/hsTanPhu9P2.jpg",
        "/images/hsTanPhu10P2.jpg",
        "/images/hsTanPhu11P2.jpg",
        "/images/hsTanPhu12P2.jpg",
      ],
      amenities: [
        "máy lạnh",
        "máy chiếu",
        "bếp",
        "nước nóng lạnh",
        "YouTube Premium",
        "Netflix",
      ],
      price: "/images/P-Tangerine.png",
      description:
        "Tươi sáng và tràn đầy sức sống, Tangerine là lựa chọn hoàn hảo cho những ai yêu thích sự năng động nhưng vẫn muốn tìm kiếm sự bình yên trong không gian sống. Lấy cảm hứng từ sắc cam của trái quýt chín mọng, homestay sử dụng gam màu ấm áp, nhẹ nhàng kết hợp cùng ánh sáng tự nhiên để tạo nên không khí gần gũi và thoải mái. Đây là nơi lý tưởng để bạn khơi dậy năng lượng tích cực mỗi ngày.",
    },
    {
      id: 3,
      slug: "mocha",
      name: "Mocha",
      address: "Quận Tân Phú, TP. HCM",
      district: "Quận Tân Phú",
      video: "/videos/hsTanPhu.mp4",
      images: [
        "/images/hsTanPhu1P3.jpg",
        "/images/hsTanPhu2P3.jpg",
        "/images/hsTanPhu3P3.jpg",
        "/images/hsTanPhu4P3.jpg",
        "/images/hsTanPhu5P3.jpg",
        "/images/hsTanPhu6P3.jpg",
        "/images/hsTanPhu7P3.jpg",
        "/images/hsTanPhu8P3.jpg",
        "/images/hsTanPhu9P3.jpg",
        "/images/hsTanPhu10P3.jpg",
        "/images/hsTanPhu11P3.jpg",
        "/images/hsTanPhu12P3.jpg",
        "/images/hsTanPhu13P3.jpg",
      ],
      amenities: [
        "máy lạnh",
        "máy chiếu",
        "bếp",
        "nước nóng lạnh",
        "YouTube Premium",
        "Netflix",
      ],
      price: "/images/P-Mocha.png",
      description:
        "Nếu bạn đang tìm kiếm một nơi vừa ấm cúng, vừa hiện đại thì Mocha chính là câu trả lời. Tông màu nâu nhẹ của gỗ kết hợp cùng nội thất tinh giản, tạo nên không gian vừa sang trọng vừa gợi cảm giác thân quen như một tách cà phê mocha ngọt ngào. Homestay này là chốn về lý tưởng cho những người yêu thích sự tĩnh lặng và thanh lịch trong cuộc sống đô thị.",
    },
    {
      id: 4,
      slug: "miso",
      name: "Miso",
      address: "Quận 10, TP. HCM",
      district: "Quận 10",
      video: "",
      images: [
        "/images/hsToHienThanhP1.jpg",
        "/images/hsToHienThanh1P1.jpg",
        "/images/hsToHienThanh2P1.jpg",
        "/images/hsToHienThanh3P1.jpg",
        "/images/hsToHienThanh4P1.jpg",
        "/images/hsToHienThanh5P1.jpg",
        "/images/hsToHienThanh6P1.jpg",
        "/images/hsToHienThanh7P1.jpg",
        "/images/hsToHienThanh8P1.jpg",
        "/images/hsToHienThanh9P1.jpg",
        "/images/hsToHienThanh10P1.jpg",
        "/images/hsToHienThanh11P1.jpg",
        "/images/hsToHienThanh12P1.jpg",
      ],
      amenities: [
        "máy lạnh",
        "máy chiếu",
        "bếp",
        "nước nóng lạnh",
        "YouTube Premium",
        "Netflix",
      ],
      price: "/images/P-Miso.png",
      description:
        "Tựa như một bát súp miso nhẹ nhàng và ấm lòng, homestay này mang đến không gian thư giãn nhẹ nhàng giữa lòng thành phố sôi động. Thiết kế hướng đến sự tối giản, tinh tế và đậm chất thiền, kết hợp ánh sáng dịu nhẹ và chất liệu tự nhiên như gỗ và vải thô, tạo cảm giác yên bình và thư giãn tuyệt đối. Miso là lựa chọn lý tưởng cho những ai đang tìm kiếm một nơi để “dừng lại” và hồi phục năng lượng.",
    },
    {
      id: 5,
      slug: "halo",
      name: "Halo",
      address: "Quận 10, TP. HCM",
      district: "Quận 10",
      video: "",
      images: [
        "/images/hsToHienThanhP2.jpg",
        "/images/hsToHienThanh1P2.jpg",
        "/images/hsToHienThanh2P2.jpg",
        "/images/hsToHienThanh3P2.jpg",
        "/images/hsToHienThanh4P2.jpg",
        "/images/hsToHienThanh5P2.jpg",
        "/images/hsToHienThanh6P2.jpg",
        "/images/hsToHienThanh7P2.jpg",
        "/images/hsToHienThanh8P2.jpg",
        "/images/hsToHienThanh9P2.jpg",
        "/images/hsToHienThanh10P2.jpg",
        "/images/hsToHienThanh11P2.jpg",
        "/images/hsToHienThanh12P2.jpg",
        "/images/hsToHienThanh13P2.jpg",
        "/images/hsToHienThanh14P2.jpg",
        "/images/hsToHienThanh15P2.jpg",
      ],
      amenities: [
        "máy lạnh",
        "máy chiếu",
        "bếp",
        "nước nóng lạnh",
        "YouTube Premium",
        "Netflix",
      ],
      price: "/images/P-Halo.png",
      description:
        "Mang dáng dấp của một vầng hào quang nhẹ nhàng, Halo chinh phục du khách bằng sự thanh thoát trong từng chi tiết. Tông trắng chủ đạo được tô điểm bằng ánh sáng vàng ấm, tạo nên một không gian tinh khiết, hiện đại mà không kém phần ấm cúng. Đây là lựa chọn hoàn hảo cho các cặp đôi hoặc những ai yêu thích sự gọn gàng, nhẹ nhàng và tinh tế.",
    },
    {
      id: 6,
      slug: "dust",
      name: "Dust",
      address: "Quận Bình Thạnh, TP. HCM",
      district: "Quận Bình Thạnh",
      video: "",
      images: [
        "/images/hsBinhThanhXVNT1P1.jpg",
        "/images/hsBinhThanhXVNT2P1.jpg",
        "/images/hsBinhThanhXVNT3P1.jpg",
        "/images/hsBinhThanhXVNT4P1.jpg",
        "/images/hsBinhThanhXVNT5P1.jpg",
        "/images/hsBinhThanhXVNT6P1.jpg",
        "/images/hsBinhThanhXVNT7P1.jpg",
        "/images/hsBinhThanhXVNT8P1.jpg",
        "/images/hsBinhThanhXVNT9P1.jpg",
        "/images/hsBinhThanhXVNT10P1.jpg",
        "/images/hsBinhThanhXVNT11P1.jpg",
        "/images/hsBinhThanhXVNT12P1.jpg",
        "/images/hsBinhThanhXVNT13P1.jpg",
      ],
      amenities: [
        "máy lạnh",
        "view đẹp",
        "máy chiếu",
        "bếp",
        "nước nóng lạnh",
        "YouTube Premium",
        "Netflix",
      ],
      price: "/images/P-Dust.png",
      description:
        "Lấy cảm hứng từ sự mộc mạc của thiên nhiên, Dust mang đến trải nghiệm sống chân thật và gần gũi. Không gian sử dụng tông màu trung tính, nội thất gỗ thô mộc và ánh sáng tự nhiên làm chủ đạo. Đây là nơi giúp bạn trút bỏ mọi muộn phiền và trở về với chính mình trong sự yên tĩnh, đơn sơ nhưng đầy tinh tế.",
    },
    {
      id: 7,
      slug: "rustic",
      name: "Rustic",
      address: "Quận Bình Thạnh, TP. HCM",
      district: "Quận Bình Thạnh",
      video: "",
      images: [
        "/images/hsBinhThanhXVNT1P2.jpg",
        "/images/hsBinhThanhXVNT2P2.jpg",
        "/images/hsBinhThanhXVNT3P2.jpg",
        "/images/hsBinhThanhXVNT4P2.jpg",
        "/images/hsBinhThanhXVNT5P2.jpg",
        "/images/hsBinhThanhXVNT6P2.jpg",
        "/images/hsBinhThanhXVNT7P2.jpg",
        "/images/hsBinhThanhXVNT8P2.jpg",
        "/images/hsBinhThanhXVNT9P2.jpg",
        "/images/hsBinhThanhXVNT10P2.jpg",
        "/images/hsBinhThanhXVNT11P2.jpg",
        "/images/hsBinhThanhXVNT12P2.jpg",
        "/images/hsBinhThanhXVNT13P2.jpg",
      ],
      amenities: [
        "máy lạnh",
        "bồn tắm",
        "view đẹp",
        "máy chiếu",
        "bếp",
        "nước nóng lạnh",
        "YouTube Premium",
        "Netflix",
      ],
      price: "/images/P-Rustic.png",
      description:
        "Rustic là nơi mà nét đẹp mộc mạc và phong cách cổ điển giao thoa một cách hoàn hảo. Những chi tiết tưởng chừng như cũ kỹ lại được sắp đặt một cách có chủ đích, mang đến một không gian trầm lắng nhưng đầy chất thơ. Đây là chốn nghỉ ngơi lý tưởng cho những ai yêu sự hoài niệm, nhưng vẫn muốn tận hưởng tiện nghi hiện đại.",
    },
    {
      id: 8,
      slug: "moss",
      name: "Moss",
      address: "Quận 4, TP. HCM",
      district: "Quận 4",
      video: "/videos/hsXomChieu.mp4",
      images: [
        "/images/hsXomChieu1P1.jpg",
        "/images/hsXomChieu2P1.jpg",
        "/images/hsXomChieu3P1.jpg",
        "/images/hsXomChieu4P1.jpg",
        "/images/hsXomChieu5P1.jpg",
      ],
      amenities: [
        "máy lạnh",
        "máy chiếu",
        "bếp",
        "nước nóng lạnh",
        "YouTube Premium",
        "Netflix",
      ],
      price: "/images/P-Moss.png",
      description:
        "Ẩn mình trong những con phố nhỏ của Quận 4, Moss như một khoảng xanh tĩnh lặng giữa lòng đô thị. Thiết kế không gian mang đậm chất tự nhiên với sắc xanh dịu mắt, nội thất tối giản cùng các vật liệu mộc mạc như gỗ và đá, mang đến cảm giác gần gũi và thân thiện. Moss là nơi để bạn sống chậm lại, hòa mình vào thiên nhiên giữa lòng thành phố.",
    },
    {
      id: 9,
      slug: "cream",
      name: "Cream",
      address: "Quận 4, TP. HCM",
      district: "Quận 4",
      video: "/videos/hsXomChieu.mp4",
      images: [
        "/images/hsXomChieu1P2.jpg",
        "/images/hsXomChieu2P2.jpg",
        "/images/hsXomChieu3P2.jpg",
        "/images/hsXomChieu4P2.jpg",
        "/images/hsXomChieu5P2.jpg",
      ],
      amenities: [
        "máy lạnh",
        "máy chiếu",
        "bếp",
        "nước nóng lạnh",
        "YouTube Premium",
        "Netflix",
      ],
      price: "/images/P-Cream.png",
      description:
        "Với gam màu kem làm chủ đạo, Cream mang đến sự nhẹ nhàng, thanh thoát và sang trọng. Từng chi tiết trong không gian đều được chăm chút tỉ mỉ để tạo nên một tổng thể hài hòa, phù hợp cho cả kỳ nghỉ dài ngày hay những buổi “getaway” cuối tuần. Đây là lựa chọn tuyệt vời dành cho những tâm hồn yêu sự trang nhã, dịu dàng.",
    },
    {
      id: 10,
      slug: "nude",
      name: "Nude",
      address: "Quận 6, TP. HCM",
      district: "Quận 6",
      video: "",
      images: [
        "/images/nude00.jpg",
        "/images/nude01.jpg",
        "/images/nude02.jpg",
        "/images/nude03.jpg",
        "/images/nude04.jpg",
        "/images/nude05.jpg",
        "/images/nude06.jpg",
        "/images/nude07.jpg",
        "/images/nude08.jpg",
        "/images/nude09.jpg",
        "/images/nude10.jpg",
        "/images/nude11.jpg",
        "/images/nude12.jpg",
        "/images/nude13.jpg",
        "/images/nude14.jpg",
        "/images/nude15.jpg",
        "/images/nude16.jpg",
        "/images/nude17.jpg",
        "/images/nude18.jpg",
        "/images/nude19.jpg",
      ],
      amenities: [
        "máy lạnh",
        "view đẹp",
        "máy chiếu",
        "bếp",
        "nước nóng lạnh",
        "YouTube Premium",
        "Netflix",
      ],
      price: "/images/P-Nude.png",
      description:
        "Phong cách tối giản chính là tinh thần của Nude. Không gian được thiết kế với tông nude nhẹ nhàng, kết hợp cùng ánh sáng tự nhiên và nội thất tinh giản, mang đến sự thanh lịch, hiện đại nhưng vẫn gần gũi. Homestay này phù hợp với những ai yêu sự cân bằng, không quá cầu kỳ nhưng vẫn toát lên nét đẹp sang trọng rất riêng.",
    },
    {
      id: 11,
      slug: "dark",
      name: "Dark",
      address: "Quận 6, TP. HCM",
      district: "Quận 6",
      video: "",
      images: [
        "/images/dark00.jpg",
        "/images/dark1.jpg",
        "/images/dark2.jpg",
        "/images/dark3.jpg",
        "/images/dark4.jpg",
        "/images/dark5.jpg",
        "/images/dark6.jpg",
        "/images/dark7.jpg",
        "/images/dark8.jpg",
        "/images/dark9.jpg",
        "/images/dark10.jpg",
        "/images/dark11.jpg",
        "/images/dark12.jpg",
        "/images/dark13.jpg",
        "/images/dark14.jpg",
        "/images/dark15.jpg",
        "/images/dark16.jpg",
        "/images/dark17.jpg",
        "/images/dark18.jpg",
        "/images/dark19.jpg",
      ],
      amenities: [
        "máy lạnh",
        "bồn tắm",
        "view đẹp",
        "máy chiếu",
        "bếp",
        "nước nóng lạnh",
        "YouTube Premium",
        "Netflix",
      ],
      price: "/images/P-Dark.png",
      description:
        "Khác biệt hoàn toàn với những homestay còn lại, Dark mang vẻ đẹp của sự huyền bí và cá tính. Tông màu tối mạnh mẽ kết hợp cùng ánh sáng dịu nhẹ tạo nên một không gian ấm cúng, riêng tư và đầy chiều sâu. Đây là lựa chọn hoàn hảo cho những ai tìm kiếm trải nghiệm độc đáo, đầy chất “nghệ” giữa lòng Sài Gòn.",
    },
  ];

  return new Response(JSON.stringify(homeStays), {
    headers: { "Content-Type": "application/json" },
  });
}
