export async function GET() {
  const homeStays = [
    {
      id: 1,
      slug: "23sthomestay-tan-phu-phong-1",
      name: "23st.homestay Tân Phú Phòng 1",
      address: "Quận Tân Phú, TP. HCM",
      district: "Quận Tân Phú",
      video: "/videos/hsTanPhu.mp4",
      images: [
        "/images/hsTanPhu1P1.jpg",
        "/images/hsTanPhu2P1.jpg",
        "/images/hsTanPhu3P1.jpg",
        "/images/hsTanPhu4P1.jpg",
        "/images/hsTanPhu5P1.jpg",
        "/images/hsTanPhu6P1.jpg",
        "/images/hsTanPhu7P1.jpg",
        "/images/hsTanPhu8P1.jpg",
        "/images/hsTanPhu9P1.jpg",
        "/images/hsTanPhu10P1.jpg",
        "/images/hsTanPhu11P1.jpg",
        "/images/hsTanPhu12P1.jpg",
        "/images/hsTanPhu13P1.jpg",
      ],
      description: "Mô tả chi tiết cho homestay Bình Thạnh.",
    },
    {
      id: 2,
      slug: "23sthomestay-tan-phu-phong-2",
      name: "23st.homestay Tân Phú Phòng 2",
      address: "Quận Tân Phú, TP. HCM",
      district: "Quận Tân Phú",
      video: "/videos/hsTanPhu.mp4",
      images: [
        "/images/hsTanPhu1P2.jpg",
        "/images/hsTanPhu2P2.jpg",
        "/images/hsTanPhu3P2.jpg",
        "/images/hsTanPhu4P2.jpg",
        "/images/hsTanPhu5P2.jpg",
        "/images/hsTanPhu6P2.jpg",
        "/images/hsTanPhu7P2.jpg",
        "/images/hsTanPhu8P2.jpg",
        "/images/hsTanPhu9P2.jpg",
        "/images/hsTanPhu10P2.jpg",
        "/images/hsTanPhu11P2.jpg",
        "/images/hsTanPhu12P2.jpg",
      ],
      description: "Mô tả chi tiết cho homestay Bình Thạnh.",
    },
    {
      id: 3,
      slug: "23sthomestay-tan-phu-phong-3",
      name: "23st.homestay Tân Phú Phòng 3",
      address: "Quận Tân Phú, TP. HCM",
      district: "Quận Tân Phú",
      video: "/videos/hsTanPhu.mp4",
      images: [
        "/images/hsTanPhu1P3.jpg",
        "/images/hsTanPhu2P3.jpg",
        "/images/hsTanPhu3P3.jpg",
        "/images/hsTanPhu4P3.jpg",
        "/images/hsTanPhu5P3.jpg",
        "/images/hsTanPhu6P3.jpg",
        "/images/hsTanPhu7P3.jpg",
        "/images/hsTanPhu8P3.jpg",
        "/images/hsTanPhu9P3.jpg",
        "/images/hsTanPhu10P3.jpg",
        "/images/hsTanPhu11P3.jpg",
        "/images/hsTanPhu12P3.jpg",
        "/images/hsTanPhu13P3.jpg",
      ],
      description: "Mô tả chi tiết cho homestay Bình Thạnh.",
    },
    {
      id: 4,
      slug: "23sthomestay-quan-10-to-hien-thanh-phong-1",
      name: "23st.homestay Quận 10 Tô Hiến Thành Phòng 1",
      address: "Quận 10, TP. HCM",
      district: "Quận 10",
      video: "",
      images: [
        "/images/hsToHienThanhP1.jpg",
        "/images/hsToHienThanh1P1.jpg",
        "/images/hsToHienThanh2P1.jpg",
        "/images/hsToHienThanh3P1.jpg",
        "/images/hsToHienThanh4P1.jpg",
        "/images/hsToHienThanh5P1.jpg",
        "/images/hsToHienThanh6P1.jpg",
        "/images/hsToHienThanh7P1.jpg",
        "/images/hsToHienThanh8P1.jpg",
        "/images/hsToHienThanh9P1.jpg",
        "/images/hsToHienThanh10P1.jpg",
        "/images/hsToHienThanh11P1.jpg",
        "/images/hsToHienThanh12P1.jpg",
      ],
      description: "Mô tả chi tiết cho homestay Bình Thạnh.",
    },
    {
      id: 5,
      slug: "23sthomestay-quan-10-to-hien-thanh-phong-2",
      name: "23st.homestay Quận 10 Tô Hiến Thành Phòng 2",
      address: "Quận 10, TP. HCM",
      district: "Quận 10",
      video: "",
      images: [
        "/images/hsToHienThanhP2.jpg",
        "/images/hsToHienThanh1P2.jpg",
        "/images/hsToHienThanh2P2.jpg",
        "/images/hsToHienThanh3P2.jpg",
        "/images/hsToHienThanh4P2.jpg",
        "/images/hsToHienThanh5P2.jpg",
        "/images/hsToHienThanh6P2.jpg",
        "/images/hsToHienThanh7P2.jpg",
        "/images/hsToHienThanh8P2.jpg",
        "/images/hsToHienThanh9P2.jpg",
        "/images/hsToHienThanh10P2.jpg",
        "/images/hsToHienThanh11P2.jpg",
        "/images/hsToHienThanh12P2.jpg",
        "/images/hsToHienThanh13P2.jpg",
        "/images/hsToHienThanh14P2.jpg",
        "/images/hsToHienThanh15P2.jpg",
      ],
      description: "Mô tả chi tiết cho homestay Bình Thạnh.",
    },
    {
      id: 6,
      slug: "23sthomestay-quan-binh-thanh-xo-viet-nghe-tinh-phong-1",
      name: "23st.homestay Quận Bình Thạnh Xô Viết Nghệ Tĩnh Phòng 1",
      address: "Quận Bình Thạnh, TP. HCM",
      district: "Quận Bình Thạnh",
      video: "",
      images: [
        "/images/hsBinhThanhXVNT1P1.jpg",
        "/images/hsBinhThanhXVNT2P1.jpg",
        "/images/hsBinhThanhXVNT3P1.jpg",
        "/images/hsBinhThanhXVNT4P1.jpg",
        "/images/hsBinhThanhXVNT5P1.jpg",
        "/images/hsBinhThanhXVNT6P1.jpg",
        "/images/hsBinhThanhXVNT7P1.jpg",
        "/images/hsBinhThanhXVNT8P1.jpg",
        "/images/hsBinhThanhXVNT9P1.jpg",
        "/images/hsBinhThanhXVNT10P1.jpg",
        "/images/hsBinhThanhXVNT11P1.jpg",
        "/images/hsBinhThanhXVNT12P1.jpg",
        "/images/hsBinhThanhXVNT13P1.jpg",
      ],
      description: "Mô tả chi tiết cho homestay Bình Thạnh.",
    },
    {
      id: 7,
      slug: "23sthomestay-quan-binh-thanh-xo-viet-nghe-tinh-phong-2",
      name: "23st.homestay Quận Bình Thạnh Xô Viết Nghệ Tĩnh Phòng 2",
      address: "Quận Bình Thạnh, TP. HCM",
      district: "Quận Bình Thạnh",
      video: "",
      images: [
        "/images/hsBinhThanhXVNT1P2.jpg",
        "/images/hsBinhThanhXVNT2P2.jpg",
        "/images/hsBinhThanhXVNT3P2.jpg",
        "/images/hsBinhThanhXVNT4P2.jpg",
        "/images/hsBinhThanhXVNT5P2.jpg",
        "/images/hsBinhThanhXVNT6P2.jpg",
        "/images/hsBinhThanhXVNT7P2.jpg",
        "/images/hsBinhThanhXVNT8P2.jpg",
        "/images/hsBinhThanhXVNT9P2.jpg",
        "/images/hsBinhThanhXVNT10P2.jpg",
        "/images/hsBinhThanhXVNT11P2.jpg",
        "/images/hsBinhThanhXVNT12P2.jpg",
        "/images/hsBinhThanhXVNT13P2.jpg",
      ],
      description: "Mô tả chi tiết cho homestay Bình Thạnh.",
    },
    {
      id: 8,
      slug: "23sthomestay-quan-4-xom-chieu-phong-1",
      name: "23st.homestay Quận 4 Xóm Chiếu Phòng 1",
      address: "Quận 4, TP. HCM",
      district: "Quận 4",
      video: "/videos/hsXomChieu.mp4",
      images: [
        "/images/hsXomChieu1P1.jpg",
        "/images/hsXomChieu2P1.jpg",
        "/images/hsXomChieu3P1.jpg",
        "/images/hsXomChieu4P1.jpg",
        "/images/hsXomChieu5P1.jpg",
      ],
      description: "Mô tả chi tiết cho homestay 4.",
    },
    {
      id: 9,
      slug: "23sthomestay-quan-4-xom-chieu-phong-2",
      name: "23st.homestay Quận 4 Xóm Chiếu Phòng 2",
      address: "Quận 4, TP. HCM",
      district: "Quận 4",
      video: "/videos/hsXomChieu.mp4",
      images: [
        "/images/hsXomChieu1P2.jpg",
        "/images/hsXomChieu2P2.jpg",
        "/images/hsXomChieu3P2.jpg",
        "/images/hsXomChieu4P2.jpg",
        "/images/hsXomChieu5P2.jpg",
      ],
      description: "Mô tả chi tiết cho homestay 4.",
    },
  ];

  return new Response(JSON.stringify(homeStays), {
    headers: { "Content-Type": "application/json" },
  });
}
